name: soofty
description: WhatsApp Video Status Maker.
version: 9.0.4

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.12.11
  firebase_auth: ^0.15.1
  firebase_admob: ^0.9.0+9
  google_sign_in: ^4.0.7
  cached_network_image: ^2.0.0-rc
  provider: ^3.2.0
  flutter_staggered_grid_view: ^0.3.0
  audioplayers: ^0.13.5
  permission_handler: ^4.0.0
  shared_preferences: ^0.5.4+8
  firebase_analytics: ^5.0.5
  firebase_crashlytics: ^0.1.2+2
  google_fonts: ^0.1.1
  package_info: ^0.4.0+13
  connectivity: ^0.4.6
  flutter_spinkit: ^4.1.0
  font_awesome_flutter: ^8.5.0
  smooth_star_rating: ^1.0.3
  path_provider: ^1.4.4
  image_picker: ^0.6.2+2
  image_cropper: ^1.1.1
  dio: ^3.0.7
  progress_dialog: ^1.2.0
  firebase_performance: ^0.3.1+5
  esys_flutter_share: ^1.0.2
  flutter_ffmpeg: ^0.2.8
  video_player: ^0.10.2+6
  url_launcher: ^5.2.7
  firebase_dynamic_links: ^0.5.0+8
  firebase_messaging: ^6.0.3
  flutter_local_notifications: ^0.8.4+3
  thumbnails: ^1.0.1
  # !-----------------! #
  # intro_slider: ^2.2.8
  # koukicons: ^2.0.2
  # line_icons: ^0.2.0
  # animated_text_kit: ^1.3.1
  # rosetta: ^0.1.3
  # firebase_ml_vision: ^0.9.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    # - assets/videos/
