name: soofty
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.12.11
  # firebase_messaging: ^6.0.3
  firebase_auth: ^0.15.1
  firebase_admob: ^0.9.0+9
  google_sign_in: ^4.0.7
  # firebase_dynamic_links: ^0.5.0+8
  # share: ^0.6.2+1
  # cached_network_image: ^1.1.3
  # font_awesome_flutter: ^8.5.0
  # provider: ^3.2.0
  flutter_staggered_grid_view: ^0.3.0
  # video_player: ^0.10.2+6
  # dio: ^3.0.7
  # audioplayers: ^0.13.5
  # path_provider: ^1.4.4
  permission_handler: ^4.0.0
  # firebase_storage: ^3.0.7
  # url_launcher: ^5.2.7
  # image_picker: ^0.6.2+2
  # file_picker: ^1.4.3+1
  # flutter_spinkit: ^4.1.0
  # image_cropper: ^1.1.1
  # connectivity: ^0.4.6
  # liquid_pull_to_refresh: ^1.1.1
  # progress_button: ^0.0.2
  # shimmer: ^1.0.1
  # animated_text_kit: ^1.3.1
  # flip_card: ^0.4.4
  # material_design_icons_flutter: ^3.4.4595
  # intro_slider: ^2.2.8
  intro_views_flutter: ^2.8.0
  # smooth_star_rating: ^1.0.3
  # progress_dialog: ^1.2.0
  # rosetta: ^0.1.3
  # flutter_local_notifications: ^0.8.4+3
  # shared_preferences: ^0.5.4+8
  # sembast: ^2.1.2
  # flutter_ffmpeg: ^0.2.8
  google_fonts: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
